// Guards for the places where text ends up inside a SQL statement without going through
// bound parameters: identifiers (table/column names) and SQL generated by the LLM.

export class InvalidInputError extends Error {}

// Lowercase only: unquoted identifiers are folded to lowercase by PostgreSQL, and the SQL
// written by the LLM refers to tables that way.
const TABLE_NAME_PATTERN = /^[a-z_][a-z0-9_]{0,62}$/;
const INTERNAL_TABLES = new Set(['table_schema']);

export function quoteIdent(identifier: string): string {
  return `"${identifier.replace(/"/g, '""')}"`;
}

export function parseTableName(raw: unknown): string {
  if (typeof raw !== 'string' || !raw.trim()) {
    throw new InvalidInputError('Table name is required');
  }
  const tableName = raw.trim().toLowerCase();
  if (!TABLE_NAME_PATTERN.test(tableName)) {
    throw new InvalidInputError(
      'Invalid table name: use only letters, digits and underscores, start with a letter or underscore (63 characters max)'
    );
  }
  if (INTERNAL_TABLES.has(tableName) || tableName.startsWith('pg_')) {
    throw new InvalidInputError(`Table name "${tableName}" is reserved`);
  }
  return tableName;
}

// Leading whitespace and SQL comments are allowed before the first keyword.
const LEADING_NOISE = /^(?:\s+|--[^\n]*(?:\n|$)|\/\*[\s\S]*?\*\/)*/;

// Only plain reads are accepted. This rejects COPY, DO, CALL, SET and every write statement
// before they reach the database; queryReadOnly() enforces the rest at the database level.
export function assertSelectQuery(sql: unknown): string {
  if (typeof sql !== 'string' || !sql.trim()) {
    throw new Error('The generated SQL query is empty');
  }
  const body = sql.replace(LEADING_NOISE, '');
  if (!/^(select|with)\b/i.test(body)) {
    throw new Error('Only SELECT queries are allowed. Rewrite the query as a single SELECT statement.');
  }
  return sql;
}
